# Generated by Django 6.0.6 on 2026-07-11 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='eliminado',
            field=models.BooleanField(default=False),
        ),
    ]
