# Generated by Django 6.0.6 on 2026-07-16 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('objetivosI', '0002_historialobjetivoinstitucional'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObjetivoEstrategico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=30, unique=True)),
                ('descripcion', models.TextField()),
                ('eje_estrategico', models.CharField(max_length=150)),
                ('periodo_vigencia', models.CharField(max_length=50)),
                ('estado', models.BooleanField(default=True)),
                ('objetivos_institucionales', models.ManyToManyField(blank=True, related_name='objetivos_estrategicos', to='objetivosI.objetivoinstitucional')),
            ],
            options={
                'verbose_name': 'Objetivo Estratégico',
                'verbose_name_plural': 'Objetivos Estratégicos',
                'db_table': 'objetivo_estrategico',
            },
        ),
    ]
