# Generated by Django 6.0.6 on 2026-07-15 01:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('proyectos', '0004_alter_cronograma_porcentaje_avance_documento'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ObjetivoInstitucional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('descripcion', models.TextField()),
                ('periodo_vigencia', models.CharField(max_length=20)),
                ('estado', models.BooleanField(default=True)),
                ('proyectos', models.ManyToManyField(blank=True, related_name='objetivos_institucionales', to='proyectos.proyecto')),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Objetivo Institucional',
                'verbose_name_plural': 'Objetivos Institucionales',
                'db_table': 'objetivo_institucional',
            },
        ),
    ]
