# Generated by Django 6.0.6 on 2026-07-10 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_recuperacionpassword'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='bloqueado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usuario',
            name='intentos_fallidos',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
