# Generated by Django 6.0.6 on 2026-07-10 21:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_usuario_bloqueado_usuario_intentos_fallidos'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditoriaSesion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(max_length=30)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auditorias', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Auditoría de sesión',
                'verbose_name_plural': 'Auditorías de sesión',
                'db_table': 'auditoria_sesion',
            },
        ),
    ]
