# Generated by Django 6.0.6 on 2026-07-19 22:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('Usuarios', 'Usuarios'), ('Entidades', 'Entidades'), ('Planificaciones', 'Planificaciones'), ('Proyectos', 'Proyectos'), ('ODS', 'ODS'), ('Metas', 'Metas'), ('Indicadores', 'Indicadores'), ('Avances', 'Avances')], max_length=30)),
                ('fecha_generacion', models.DateTimeField(auto_now_add=True)),
                ('archivo_pdf', models.FileField(blank=True, null=True, upload_to='reportes/pdf/')),
                ('archivo_excel', models.FileField(blank=True, null=True, upload_to='reportes/excel/')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reporte',
                'verbose_name_plural': 'Reportes',
                'db_table': 'reporte',
            },
        ),
    ]
