# Generated by Django 6.0.6 on 2026-07-12 16:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguimiento', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialMeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('descripcion', models.TextField()),
                ('meta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seguimiento.meta')),
            ],
            options={
                'db_table': 'historial_meta',
            },
        ),
    ]
