# Generated by Django 6.0.6 on 2026-07-13 19:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguimiento', '0002_historialmeta'),
    ]

    operations = [
        migrations.CreateModel(
            name='Indicador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('formula', models.CharField(max_length=200)),
                ('unidad_medida', models.CharField(max_length=50)),
                ('frecuencia', models.CharField(max_length=50)),
                ('estado', models.BooleanField(default=True)),
                ('meta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indicadores', to='seguimiento.meta')),
            ],
            options={
                'verbose_name': 'Indicador',
                'verbose_name_plural': 'Indicadores',
                'db_table': 'indicador',
            },
        ),
        migrations.CreateModel(
            name='AvanceIndicador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('porcentaje_cumplimiento', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('indicador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avances', to='seguimiento.indicador')),
            ],
            options={
                'db_table': 'avance_indicador',
            },
        ),
    ]
