# Generated by Django 6.0.6 on 2026-07-19 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguimiento', '0003_indicador_avanceindicador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meta',
            name='descripcion',
            field=models.CharField(max_length=500),
        ),
    ]
