# Generated by Django 6.0.6 on 2026-07-19 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguimiento', '0004_alter_meta_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meta',
            name='descripcion',
            field=models.CharField(max_length=1000),
        ),
    ]
