# Generated by Django 6.0.6 on 2026-07-19 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguimiento', '0005_alter_meta_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicador',
            name='nombre',
            field=models.CharField(max_length=1000),
        ),
    ]
