# Generated by Django 6.0.6 on 2026-07-14 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('proyectos', '0004_alter_cronograma_porcentaje_avance_documento'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObjetivoDesarrollo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('descripcion', models.TextField()),
                ('eje_estrategico', models.CharField(max_length=200)),
                ('periodo_vigencia', models.CharField(max_length=100)),
                ('proyectos', models.ManyToManyField(blank=True, related_name='objetivos_desarrollo', to='proyectos.proyecto')),
            ],
            options={
                'verbose_name': 'Objetivo de Desarrollo',
                'verbose_name_plural': 'Objetivos de Desarrollo',
                'db_table': 'objetivo_desarrollo',
            },
        ),
    ]
