# Generated by Django 6.0.6 on 2026-07-14 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ods', '0001_initial'),
        ('seguimiento', '0003_indicador_avanceindicador'),
    ]

    operations = [
        migrations.AddField(
            model_name='objetivodesarrollo',
            name='metas',
            field=models.ManyToManyField(blank=True, related_name='objetivos_desarrollo', to='seguimiento.meta'),
        ),
    ]
