# Generated by Django 6.0.6 on 2026-07-14 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ods', '0002_objetivodesarrollo_metas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='objetivodesarrollo',
            name='metas',
        ),
    ]
