# Generated by Django 6.0.6 on 2026-07-14 20:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ods', '0003_remove_objetivodesarrollo_metas'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialObjetivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('descripcion', models.CharField(max_length=250)),
                ('objetivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='ods.objetivodesarrollo')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Historial Objetivo',
                'verbose_name_plural': 'Historial Objetivos',
                'db_table': 'historial_objetivo',
            },
        ),
    ]
