# Generated by Django 6.0.6 on 2026-07-07 23:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('entidades', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Planificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo', models.CharField(max_length=20)),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('estado', models.BooleanField(default=True)),
                ('entidad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='planificaciones', to='entidades.entidad')),
            ],
            options={
                'verbose_name': 'Planificación',
                'verbose_name_plural': 'Planificaciones',
                'db_table': 'planificacion',
            },
        ),
    ]
