# Generated by Django 6.0.6 on 2026-07-08 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planificaciones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='planificacion',
            name='aprobada',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='planificacion',
            name='observacion',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='planificacion',
            name='validada',
            field=models.BooleanField(default=False),
        ),
    ]
